// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDR9TTlybpC7cdc7DvpoXE-CCp81alauA',
    appId: '1:940623941642:web:677e53671797be21f44ff3',
    messagingSenderId: '940623941642',
    projectId: 'chatapp-db71b',
    authDomain: 'chatapp-db71b.firebaseapp.com',
    storageBucket: 'chatapp-db71b.appspot.com',
    measurementId: 'G-00JD42ZB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcNb_XPIurvcpZT_EddGOuNAi_DnHhbek',
    appId: '1:940623941642:android:5c274239d80e8587f44ff3',
    messagingSenderId: '940623941642',
    projectId: 'chatapp-db71b',
    storageBucket: 'chatapp-db71b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbdSJusts9kUENdCDWaQwEIBjRqIL3hg',
    appId: '1:940623941642:ios:2cd0e1a4a90d3806f44ff3',
    messagingSenderId: '940623941642',
    projectId: 'chatapp-db71b',
    storageBucket: 'chatapp-db71b.appspot.com',
    iosClientId: '940623941642-87fcaiossue27sfjuun98c8f7sv5duom.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEbdSJusts9kUENdCDWaQwEIBjRqIL3hg',
    appId: '1:940623941642:ios:2cd0e1a4a90d3806f44ff3',
    messagingSenderId: '940623941642',
    projectId: 'chatapp-db71b',
    storageBucket: 'chatapp-db71b.appspot.com',
    iosClientId: '940623941642-87fcaiossue27sfjuun98c8f7sv5duom.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
